import type { Metadata } from "next";
import "./globals.css";
import { sampleText } from "@/data/sampleText";
import { SearchProvider } from "../hooks/useSearchContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`h-full antialiased`}>
      <SearchProvider initialText={sampleText}>
        <body className="h-full flex flex-col">{children}</body>
      </SearchProvider>
    </html>
  );
}
